EPMDJ-9927  Cookies not set for Firefox tests
Drill4J/autotest-agent pull request #91
Opened 2022-01-31 10:37 UTC by Mazel-Tovr

2022-01-31 11:22 UTC, LikhanovMaxim requested changes

2022-01-31 11:22 UTC, LikhanovMaxim commented on src/runtimeMain/kotlin/com/epam/drill/test/agent/instrumentation/http/selenium/Selenium.kt
> +        const val addDrillCookiesMethod = """addDrillCookies"""
```suggestion
        const val addDrillCookiesMethod = "addDrillCookies"
```

2022-01-31 11:22 UTC, LikhanovMaxim commented on src/runtimeMain/kotlin/com/epam/drill/test/agent/instrumentation/http/selenium/Selenium.kt
> +        private const val isFirefoxDriver = """this instanceof org.openqa.selenium.firefox.FirefoxDriver"""
```suggestion
        private const val initPages = "\"about:blank
        ", "data:,\""
        private const val isFirefoxDriver = "this instanceof org.openqa.selenium.firefox.FirefoxDriver"
```

2022-01-31 11:22 UTC, LikhanovMaxim commented on src/runtimeMain/kotlin/com/epam/drill/test/agent/instrumentation/http/selenium/Selenium.kt
> +                        if ($isFirefoxDriver && $IF_CONDITION) {
rename IF_CONDITION

2022-02-04 07:47 UTC, Mazel-Tovr commented on build.gradle.kts
> -                implementation("com.epam.drill.interceptor:http:$drillHttpInterceptorVersion")
you forgot  to remove version from gradle.properties

2022-02-04 08:08 UTC, merged